---
# tasks file for set_hostname
- name: Set hostname to '{{ hostname }}'
  become: true
  hostname:
    name: "{{ hostname }}"
  register: hostname_result

- name: Set hosts file to new hostname
  become: true
  template:
    src: hosts.j2
    dest: /etc/hosts
  register: hosts_template_result

- name: Set set_hostname_result fact
  set_fact:
    set_hostname_result:
      changed: true

